global:                                                                         
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:                                                              
      monitor: 'exporter-metrics'     

rule_files:
  - "/etc/prometheus-rules/*.yaml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093                                           
                                                                                
scrape_configs:
- job_name: 'RancherServerMetrics'
  static_configs:
    - targets:
      - 'rancher-server:9108'

- job_name: 'Prometheus'
  static_configs:
    - targets:
      - '127.0.0.1:9090'